fix(docs): invalid debug logging file
The documented file is invalid and causes
```
[01:47:57] [FTL] [1] : Failed to create/read logger configuration
System.ArgumentException: A source source must be provided. (Parameter 'source')
```